package com.jvirdi.solitaire.datatype;

public enum Location {
  DISCARD, DRAW, TABLEAU_1, TABLEAU_2, TABLEAU_3, TABLEAU_4, TABLEAU_5, TABLEAU_6, TABLEAU_7, FOUNDATION_1, FOUNDATION_2, FOUNDATION_3;
}
